
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview of Project
I've always been interested in the law and in particular case law as it is this law that becomes used as precedents in other cases where things may be a little bit more grey than simply: the law says this therefore this is the decision. Thus, when I discovered the case law dataset from the Library Innovation Lab at the Harvard Law School, I was super interested. I wanted to see how laws have changed over time. What topics are more common in modern day case law than in previous years. After all case law essentially tells us exactly what people fought over and cared about in each generation.

## Collection of Data
I was granted researcher access to the case law dataset from the Case Law Project at the Library Innovation labs. Thus, I was granted unlimited API and download access. You can find the data here: case.law

I downloaded the bulk data for all 50 states and began working with it. I immediately ran into some issues. First, the actual text of the cases were nested in a  list within a data frame within another data frame, so I had to write a function(with the help of Alyssa). to extract this and bind it to the data. A similar issue occurred with the court names and court slugs. 

I also downloaded the Supreme Court Opinions data from http://scdb.wustl.edu/ and another csv with Supreme Court Opinions from: https://www.kaggle.com/gqfiddler/scotus-opinions 

From here, my main goal was to get a sense of the development of the court system and the rise of court cases in each state. Then I wanted to assess the salience of various topics at different times in different states, and finally see how opinions of those topics have changed. 


## About the Author
This project was made by Amy Zhou, a first year who will be in Cabot House and has a love for criminal justice, law, and data. 


**Github Repo Link**: https://github.com/amyzhou9/gov1005-final-project