---
title: "opinions"
author: "Amy Zhou"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(tidyverse)
library(readxl)
library(jsonlite)
library(lubridate)
library(readr)
library(data.table)
library(reprex)
library(stringr)
library(miceadds)
```
```{r}
load.Rdata('raw-data/test.Rdata', 'op')

op <- op %>% 
  select(id, casebody) %>% 
  mutate(
    row_num = c(1:nrow(.))
  ) 

```



<!-- ```{r} -->
<!-- dat <- north_carolina$casebody %>%  -->
<!--   tail(10) -->

<!-- newdata <- dat$data -->

<!-- newnewdat <- newdata$opinions -->

<!-- x <- newnewdat[10] -->

<!-- y <- t(x) -->

<!-- b <- y[[1]]$text -->

<!-- b -->

<!-- ``` -->



```{r}
get_text <- function(row) {
  
  dat <- op$casebody 
  newdata <- dat$data
  newnewdat <- newdata$opinions
  
  x <- newnewdat[row]
  y <- t(x)
  
  y[[1]]$text
  
}
```



```{r}
texts <- op %>% 
  mutate(
    text = map(row_num, ~get_text(.))
  ) %>% 
  unnest(cols = c(text)) %>% 
  select(id, text)
```

```{r}

texts

#full_join(north_carolina, texts, by = "id")

```


