---
title: "Words Over Time"
author: "Amy Zhou"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(ggplot2)
library(miceadds)
library(ggplot2)
library(lubridate)
library(gt)

```

```{r}

load_data <- function(state){
  s <- as.character(state)
  arg <- paste("clean-data/", s, ".Rdata", sep = "")
  load.Rdata(arg, s)
  
}

read_data <- function(state){
  s <- as.character(state)
  arg <- paste("../clean-data/", s, ".rds", sep = "")
  state <- readRDS(arg)
  
}

graph_word <- function(state, word){
  
  w <- as.character(word)
  s <- as.character(state)
  arg <- paste("../clean-data/", s, ".rds", sep = "")
  t <- paste("Cases Involving", w, "in", s)
  
  state <- readRDS(arg)
  
  plot_data <- state %>% 
    select(name, decision_date, text, court_name) %>% 
    filter(grepl(word, text)) %>% 
    mutate(year = year(decision_date)) %>% 
    group_by(year) %>% 
    summarise(count = n()) %>% 
    gt()
    
}

```
```{r}
graph_word("samoa", "divorce")


```



